study_de_01_foundation:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres
      user: "{{ env_var('DBT_USER') }}"
      password: "{{ env_var('DBT_PASSWORD') }}"
      port: 5432
      dbname: "{{ env_var('DBT_DBNAME')}}"
      schema: public
      threads: 4